[package]
name = "lwactors"
version = "0.0.6"
authors = ["Ben Ashford <benashford@users.noreply.github.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
description = "Lightweight actors for Rust using futures-rs"
repository = "https://github.com/benashford/lwactors"
edition = "2018"

[dependencies]
futures-preview = { version = "=0.3.0-alpha.18", features = ["async-await", "nightly"] }

[dev-dependencies]
futures-cpupool = "0.1"
