[package]
name = "lwactors"
version = "0.0.2"
authors = ["Ben Ashford <benashford@users.noreply.github.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
description = "Lightweight actors for Rust using futures-rs"
repository = "https://github.com/benashford/lwactors"

[dependencies]
futures = "0.1.18"
futures-cpupool = "0.1.8"
