[package]
name = "lwactors"
version = "0.0.4"
authors = ["Ben Ashford <benashford@users.noreply.github.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
description = "Lightweight actors for Rust using futures-rs"
repository = "https://github.com/benashford/lwactors"

[dependencies]
futures = { version = "0.1.18", optional = true }
futures-core = { version = "0.2.1", optional = true }
futures-channel = { version = "0.2.1", optional = true }
futures-util = { version = "0.2.1", optional = true }
fut02 = { path = "./fut02", optional = true }

[dev-dependencies]
futures-cpupool = "0.1.8"

[features]
default = ["futures-01"]
futures-01 = ["futures"]
futures-02 = ["fut02", "futures-core", "futures-channel", "futures-util"]